import React from "react";
import AppShell from '@/Layouts/AppShell';
import { Badge, Button, Card, EmptyState, PageHeader, Pagination } from '@/Components/ui';
import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import { BookOpen, Pencil, Plus, Trash2, Layers } from 'lucide-react';
import { PageProps } from '@/types';

type Lesson = { id: number; title: string; status: string; unit?: string | null; course?: string | null; blocksCount: number; createdAt?: string; createdBy?: string; canEdit: boolean };
type Option = { id: number; name: string; code?: string };
type Filters = { teacher_id?: string; classroom_id?: string; date?: string };
type LessonSet = { id: number; title: string; status: string; items: Array<{ id: number; position: number; lesson?: { id: number; title: string; status: string } | null }> };

export default function Lessons({ lessons, lessonSets = [], teachers = [], classrooms = [], filters = {} }: { lessons: { data: Lesson[]; links: Array<{ url: string | null; label: string; active: boolean }> }; lessonSets?: LessonSet[]; teachers?: Option[]; classrooms?: Option[]; filters?: Filters }) {
    const { auth } = usePage<PageProps>().props;
    const prefix = auth.role === 'ADMIN' ? '/admin' : '/teacher';
    const isAdmin = auth.role === 'ADMIN';
    const form = useForm({ title: '' });
    const setForm = useForm({ title: '', lesson_ids: [] as number[] });
    const [selectedLessons, setSelectedLessons] = React.useState<number[]>([]);
    const createLesson = (event: React.FormEvent) => { event.preventDefault(); form.post(`${prefix}/lessons`, { preserveScroll: true, onSuccess: () => form.reset() }); };
    const deleteLesson = (id: number) => { if (window.confirm('Xóa vĩnh viễn Lesson này và toàn bộ bài làm, điểm số của học sinh? Hành động này không thể hoàn tác.')) router.delete(`${prefix}/lessons/${id}`); };
    const applyFilters = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); router.get(prefix + '/lessons', data, { preserveState: true, replace: true }); };
    const createSet = (event: React.FormEvent) => { event.preventDefault(); setForm.transform(data => ({ ...data, lesson_ids: selectedLessons })); setForm.post(prefix + '/lesson-sets', { preserveScroll: true, onSuccess: () => { setForm.reset(); setSelectedLessons([]); } }); };
    const toggleLesson = (id: number) => setSelectedLessons(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
    return <AppShell><Head title="Lesson Builder" /><PageHeader title="Lesson Builder" description={isAdmin ? 'Quản lý toàn bộ bài tập độc lập do trung tâm và giáo viên tạo.' : 'Tạo bài tập độc lập để giao trực tiếp cho học sinh.'} actions={<form onSubmit={createLesson} className="flex flex-wrap items-center gap-2"><input className="field w-56" value={form.data.title} onChange={event => form.setData('title', event.target.value)} placeholder="Tiêu đề bài tập" aria-label="Tiêu đề bài tập" required /><Button type="submit" loading={form.processing} leadingIcon={<Plus size={16} />}>Bài tập mới</Button></form>} />
        {isAdmin && <Card className="mt-6 p-4"><form onSubmit={applyFilters} className="grid gap-3 md:grid-cols-4"><select className="field" name="teacher_id" defaultValue={filters.teacher_id ?? ''}><option value="">Tất cả giáo viên</option>{teachers.map(teacher => <option key={teacher.id} value={teacher.id}>{teacher.name}</option>)}</select><select className="field" name="classroom_id" defaultValue={filters.classroom_id ?? ''}><option value="">Tất cả lớp được phân công</option>{classrooms.map(classroom => <option key={classroom.id} value={classroom.id}>{classroom.name}{classroom.code ? ` · ${classroom.code}` : ''}</option>)}</select><input className="field" type="date" name="date" defaultValue={filters.date ?? ''} aria-label="Lọc theo ngày tạo" /><div className="flex gap-2"><Button type="submit">Lọc</Button><Link href="/admin/lessons" className="btn-secondary">Xóa lọc</Link></div></form></Card>}
        {selectedLessons.length > 0 && <Card className="mt-6 border-indigo-100 bg-indigo-50 p-4"><form onSubmit={createSet} className="flex flex-wrap items-end gap-3"><label className="min-w-64 flex-1"><span className="label">Tên tệp đề</span><input className="field bg-white" value={setForm.data.title} onChange={event => setForm.setData("title", event.target.value)} placeholder="Ví dụ: Đề ôn tập Unit 1" required /></label><span className="pb-2 text-sm font-medium text-indigo-800">{selectedLessons.length} lesson đã chọn</span><Button type="submit" loading={setForm.processing} leadingIcon={<Layers size={16} />}>Tạo tệp đề</Button></form>{Object.values(setForm.errors).map((error, index) => <p key={index} className="mt-2 text-sm text-red-600">{error}</p>)}</Card>}
        {lessonSets.length > 0 && <Card className="mt-6 p-5"><div className="flex items-center justify-between"><div><h2 className="section-title">Tệp đề đã tạo</h2><p className="mt-1 text-sm text-slate-500">Mỗi tệp đề giữ thứ tự các lesson đã gom; lesson gốc không bị thay đổi.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2">{lessonSets.map(set => <div key={set.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{set.title}</h3><p className="mt-1 text-xs text-slate-500">{set.items.length} lesson · {set.status}</p></div><button type="button" className="btn btn-danger" onClick={() => { if (window.confirm("Xóa tệp đề này? Các lesson gốc vẫn được giữ nguyên.")) router.delete(prefix + "/lesson-sets/" + set.id); }}>Xóa</button></div><ol className="mt-3 list-decimal pl-5 text-sm text-slate-600">{set.items.map(item => <li key={item.id}>{item.lesson?.title ?? "Lesson không còn tồn tại"}</li>)}</ol></div>)}</div></Card>}
        <Card className="mt-6">{lessons.data.length ? <div className="divide-y divide-slate-100">{lessons.data.map(lesson => <div key={lesson.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><input type="checkbox" className="mt-1 h-5 w-5 rounded border-slate-300 text-indigo-600" checked={selectedLessons.includes(lesson.id)} onChange={() => toggleLesson(lesson.id)} aria-label={"Chọn " + lesson.title + " vào tệp đề"} /><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-medium text-slate-900">{lesson.title}</h2><Badge value={lesson.status} /></div><p className="mt-1 text-sm text-slate-500">{lesson.blocksCount} blocks{lesson.unit ? ` · ${lesson.unit}` : ' · Bài tập độc lập'}</p>{isAdmin && <p className="mt-1 text-xs text-slate-400">Tạo bởi: {lesson.createdBy ?? 'Không xác định'} · {lesson.createdAt ? new Date(lesson.createdAt).toLocaleDateString('vi-VN') : '—'}</p>}</div>{lesson.canEdit && <div className="flex flex-wrap gap-2"><Link href={`${prefix}/lessons/${lesson.id}/builder`} className="btn-secondary"><Pencil size={16} />Mở trình xây dựng</Link><button type="button" className="btn btn-danger" onClick={() => deleteLesson(lesson.id)}><Trash2 size={16} />Xóa Lesson</button></div>}</div></div>)}</div> : <div className="p-5"><EmptyState title="Chưa có bài tập" description="Tạo bài tập đầu tiên để mở trình xây dựng." action={<BookOpen size={18} />} /></div>}<Pagination links={lessons.links} /></Card>
    </AppShell>;
}
