import AppShell from '@/Layouts/AppShell';
import { Card, EmptyState, PageHeader } from '@/Components/ui';
import { Head, Link } from '@inertiajs/react';
import { ArrowRight, CalendarClock, TrendingUp } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { usePage } from '@inertiajs/react';
import { PageProps } from '@/types';
type Props={title:string;stats:Record<string,number|string>;upcoming:Array<{title:string;classroom:string;dueAt:string;url?:string}>;recent:Array<{action:string;entity:string;at:string}>};
export default function AppDashboard({title,stats,upcoming,recent}:Props){const {auth}=usePage<PageProps>().props;const student=auth.role==='STUDENT';const chart=Object.entries(stats).slice(0,6).map(([name,value])=>({name:name.split(' ')[0],value:Number(value)||0}));if(student)return <StudentHome name={auth.user.name} stats={stats} upcoming={upcoming} recent={recent}/>;return <AppShell><Head title={title}/><PageHeader title={title} description="Tổng quan trực tiếp về hoạt động học tập và các công việc cần xử lý."/><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(stats).map(([label,value])=><Card key={label} className="stat-card"><p className="text-sm font-medium text-slate-500">{label}</p><p className="stat-value text-slate-950">{value}</p></Card>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Card className="p-5"><div className="mb-5 flex items-center gap-2"><TrendingUp className="text-indigo-600" size={20}/><h2 className="section-title">Tổng quan hoạt động</h2></div><div className="h-72" aria-label="Biểu đồ hoạt động"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tickLine={false}/><YAxis allowDecimals={false} tickLine={false}/><Tooltip/><Bar dataKey="value" fill="#4f46e5" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></Card><Upcoming items={upcoming}/></div>{recent.length>0&&<Recent items={recent}/>}</AppShell>}
function StudentHome({name,stats,upcoming,recent}:{name:string;stats:Record<string,number|string>;upcoming:Props['upcoming'];recent:Props['recent']}){return <AppShell><Head title="Học tập"/><Card className="student-hero student-home-hero p-6 sm:p-9"><div className="relative z-10 max-w-2xl"><p className="eyebrow">Không gian học tập</p><h1>Chào mừng trở lại, {name}!</h1><p className="mt-2 max-w-xl">Sẵn sàng tiếp tục hành trình tiếng Anh hôm nay?</p><Link href={upcoming[0]?.url ?? '/student/lessons'} className="btn mt-5 inline-flex bg-white text-indigo-700 shadow-sm hover:bg-indigo-50">Tiếp tục học <ArrowRight size={16}/></Link></div><div className="student-hero-art" aria-hidden="true"><span>ABC</span><i>+</i></div></Card><div className="student-section-heading mt-8"><h2>Bài học cần hoàn thành</h2><Link href="/student/lessons" className="text-sm font-semibold text-indigo-600">Xem tất cả</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{upcoming.slice(0,3).map((item,index)=><Card key={`${item.title}-${index}`} className="student-mission-card"><span className="student-skill-icon">{index===0?'READ':index===1?'GRAM':'A+'}</span><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-indigo-600">Nhiệm vụ hôm nay</p><h3 className="mt-1 text-lg font-semibold text-slate-900">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.classroom} · Hạn {new Date(item.dueAt).toLocaleDateString('vi-VN')}</p><Link href={item.url ?? '/student/lessons'} className="btn btn-primary mt-4 w-full">Bắt đầu <ArrowRight size={15}/></Link></Card>)}{!upcoming.length&&<div className="md:col-span-2 xl:col-span-3"><EmptyState title="Bạn đã hoàn thành mọi nhiệm vụ!" description="Bài học mới sẽ xuất hiện tại đây khi giáo viên giao bài."/></div>}</div><div className="student-section-heading mt-8"><h2>Tiến độ của bạn</h2><Link href="/student/grades" className="text-sm font-semibold text-indigo-600">Xem kết quả</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(stats).slice(0,4).map(([label,value])=><Card key={label} className="student-stat-card"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></Card>)}</div>{recent.length>0&&<Recent items={recent}/>}</AppShell>}
function Upcoming({items}: {items: Props['upcoming']}){return <Card className="p-5"><div className="mb-4 flex items-center gap-2"><CalendarClock className="text-teal-600" size={20}/><h2 className="section-title">Hạn sắp tới</h2></div>{items.length?<div className="space-y-3">{items.map((item,index)=><div key={index} className="rounded-xl bg-slate-50 p-4"><p className="font-medium text-slate-900">{item.title}</p><p className="mt-1 text-sm text-slate-500">{item.classroom} · {new Date(item.dueAt).toLocaleString('vi-VN')}</p>{item.url&&<Link href={item.url} className="mt-2 inline-flex items-center gap-1 text-sm font-medium text-indigo-600">Mở <ArrowRight size={15}/></Link>}</div>)}</div>:<EmptyState title="Không có hạn sắp tới" description="Hiện không còn việc nào cần xử lý."/>}</Card>}
function Recent({items}: {items: Props['recent']}){return <Card className="mt-6 p-5"><h2 className="section-title">Hoạt động gần đây</h2><div className="mt-4 divide-y divide-slate-100">{items.map((item,index)=><div key={index} className="flex justify-between gap-4 py-3 text-sm"><span>{item.action.replaceAll('_',' ')}</span><span className="text-slate-500">{new Date(item.at).toLocaleString('vi-VN')}</span></div>)}</div></Card>}
