import AppShell from '@/Layouts/AppShell';
import { useState } from 'react';
import { Card, EmptyState, PageHeader } from '@/Components/ui';
import { Head, Link } from '@inertiajs/react';
import { ArrowRight, CalendarClock } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { usePage } from '@inertiajs/react';
import { PageProps } from '@/types';
type TrendPoint = { label: string; newStudents: number; withdrawnStudents: number };
type ClassPerformance = { id: number; name: string; average: number; gradedCount: number };
type ActivityOverview = { completion: { completed: number; total: number; remaining: number; percent: number }; completionBreakdown: Array<{ name: string; value: number; color: string }>; studentTrend: { week: TrendPoint[]; month: TrendPoint[] }; classPerformance: { highest: ClassPerformance | null; lowest: ClassPerformance | null; all: ClassPerformance[] } };
type Props = { title: string; stats: Record<string, number | string>; upcoming: Array<{ title: string; classroom: string; dueAt?: string | null; url?: string; actionLabel?: string; status?: string | null }>; recent: Array<{ action: string; entity: string; at: string }>; activityOverview?: ActivityOverview };

export default function AppDashboard({ title, stats, upcoming, recent, activityOverview }: Props) {
    const { auth } = usePage<PageProps>().props;
    const student = auth.role === 'STUDENT';
    const [period, setPeriod] = useState<'week' | 'month'>('week');
    if (student) return <StudentHome name={auth.user.name} stats={stats} upcoming={upcoming} recent={recent} />;

    const overview = activityOverview ?? {
        completion: { completed: 0, total: 0, remaining: 0, percent: 0 },
        completionBreakdown: [{ name: 'Chưa có dữ liệu', value: 1, color: '#e2e8f0' }],
        studentTrend: { week: [], month: [] },
        classPerformance: { highest: null, lowest: null, all: [] },
    };
    const trend = overview.studentTrend[period];
    const chartData = overview.completion.total > 0 ? overview.completionBreakdown : [{ name: 'Chưa có dữ liệu', value: 1, color: '#e2e8f0' }];
    const highest = overview.classPerformance.highest;
    const lowest = overview.classPerformance.lowest;

    return <AppShell>
        <Head title={title} />
        <PageHeader title={title} description="Tổng quan trực tiếp về hoạt động học tập và các công việc cần xử lý." />
        <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            {Object.entries(stats).map(([label, value]) => <Card key={label} className="stat-card relative overflow-hidden"><div className="absolute -right-5 -top-5 h-20 w-20 rounded-full bg-indigo-50" /><p className="relative text-sm font-medium text-slate-500">{label}</p><p className="relative stat-value text-slate-950">{value}</p></Card>)}
        </div>
        <div className="mt-6 grid gap-6 xl:grid-cols-[.9fr_1.35fr]">
            <Card className="overflow-hidden p-0">
                <div className="bg-gradient-to-br from-indigo-600 via-violet-600 to-fuchsia-500 px-6 py-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-100">Lesson được giao</p><h2 className="mt-1 text-xl font-bold">Tiến độ hoàn thành</h2></div><span className="rounded-full bg-white/20 px-3 py-1 text-sm font-bold">{overview.completion.percent}%</span></div><p className="mt-2 text-sm text-indigo-100">Học sinh đã hoàn thành ít nhất một lesson được giao.</p></div>
                <div className="grid items-center gap-3 p-5 sm:grid-cols-[180px_1fr]">
                    <div className="relative h-44"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartData} dataKey="value" nameKey="name" innerRadius={52} outerRadius={76} paddingAngle={3} strokeWidth={0}>{chartData.map((entry, index) => <Cell key={`${entry.name}-${index}`} fill={entry.color} />)}</Pie><Tooltip formatter={(value: number) => [overview.completion.total > 0 ? value : 0, 'Học sinh']} /></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex flex-col items-center justify-center"><span className="text-3xl font-black text-slate-900">{overview.completion.percent}%</span><span className="text-xs font-semibold text-slate-500">hoàn thành</span></div></div>
                    <div className="space-y-3"><div className="rounded-2xl bg-indigo-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-indigo-600">Đã hoàn thành</p><p className="mt-1 text-2xl font-black text-indigo-900">{overview.completion.completed}</p><p className="text-xs text-indigo-700">học sinh</p></div><div className="rounded-2xl bg-slate-100 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">Chưa hoàn thành</p><p className="mt-1 text-2xl font-black text-slate-800">{overview.completion.remaining}</p><p className="text-xs text-slate-500">trên {overview.completion.total} học sinh được giao</p></div></div>
                </div>
            </Card>
            <Card className="p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal-600">Biến động học sinh</p><h2 className="mt-1 text-xl font-bold text-slate-900">Tăng mới và thôi học</h2><p className="mt-1 text-sm text-slate-500">Theo dõi xu hướng trong tuần hoặc tháng gần nhất.</p></div><div className="flex rounded-xl bg-slate-100 p-1"><button type="button" onClick={() => setPeriod('week')} className={`rounded-lg px-3 py-1.5 text-sm font-semibold transition ${period === 'week' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}>7 ngày</button><button type="button" onClick={() => setPeriod('month')} className={`rounded-lg px-3 py-1.5 text-sm font-semibold transition ${period === 'month' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}>30 ngày</button></div></div><div className="mt-4 h-64" aria-label="Biểu đồ tăng mới và thôi học"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{ top: 8, right: 8, left: -20, bottom: 0 }}><defs><linearGradient id="newStudentsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#14b8a6" stopOpacity={0.28} /><stop offset="95%" stopColor="#14b8a6" stopOpacity={0} /></linearGradient><linearGradient id="withdrawnStudentsFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#f43f5e" stopOpacity={0.2} /><stop offset="95%" stopColor="#f43f5e" stopOpacity={0} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" /><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fontSize: 11 }} interval={period === 'month' ? 4 : 0} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{ fontSize: 11 }} /><Tooltip /><Area type="monotone" dataKey="newStudents" name="Học sinh mới" stroke="#0f766e" fill="url(#newStudentsFill)" strokeWidth={2.5} /><Area type="monotone" dataKey="withdrawnStudents" name="Thôi học" stroke="#e11d48" fill="url(#withdrawnStudentsFill)" strokeWidth={2.5} /></AreaChart></ResponsiveContainer></div><div className="mt-2 flex gap-5 text-xs font-semibold"><span className="flex items-center gap-2 text-teal-700"><i className="h-2.5 w-2.5 rounded-full bg-teal-500" />Học sinh mới</span><span className="flex items-center gap-2 text-rose-700"><i className="h-2.5 w-2.5 rounded-full bg-rose-500" />Thôi học</span></div></Card>
        </div>
        <div className="mt-6 grid gap-6 xl:grid-cols-[1.25fr_1fr]">
            <Card className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Hiệu suất theo lớp</p><h2 className="mt-1 text-xl font-bold text-slate-900">Điểm trung bình bài tập</h2></div><span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">Dữ liệu đã chấm</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><PerformanceCard label="Cao nhất" item={highest} tone="emerald" /><PerformanceCard label="Thấp nhất" item={lowest} tone="rose" /></div>{overview.classPerformance.all.length > 0 && <div className="mt-5 space-y-3">{overview.classPerformance.all.map((item, index) => <div key={item.id} className="flex items-center gap-3"><span className="w-5 text-xs font-bold text-slate-400">{index + 1}</span><span className="w-32 truncate text-sm font-semibold text-slate-700">{item.name}</span><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-500 to-violet-500" style={{ width: `${Math.min(100, Math.max(0, item.average))}%` }} /></div><span className="w-14 text-right text-sm font-bold text-slate-900">{item.average.toFixed(1)}%</span></div>)}</div>}</Card>
            <Upcoming items={upcoming} />
        </div>
        {recent.length > 0 && <Recent items={recent} />}
    </AppShell>;
}
function PerformanceCard({ label, item, tone }: { label: string; item: ClassPerformance | null; tone: 'emerald' | 'rose' }) { const styles = tone === 'emerald' ? 'border-emerald-100 bg-emerald-50 text-emerald-900' : 'border-rose-100 bg-rose-50 text-rose-900'; return <div className={`rounded-2xl border p-4 ${styles}`}><p className="text-xs font-bold uppercase tracking-wide opacity-70">{label}</p>{item ? <><p className="mt-2 truncate text-lg font-black">{item.name}</p><p className="mt-1 text-3xl font-black">{item.average.toFixed(1)}%</p><p className="mt-1 text-xs opacity-70">{item.gradedCount} bài đã chấm</p></> : <p className="mt-3 text-sm font-semibold opacity-70">Chưa có điểm</p>}</div> }
function StudentHome({name,stats,upcoming,recent}:{name:string;stats:Record<string,number|string>;upcoming:Props['upcoming'];recent:Props['recent']}){return <AppShell><Head title="Học tập"/><Card className="student-hero student-home-hero p-6 sm:p-9"><div className="relative z-10 max-w-2xl"><p className="eyebrow">Không gian học tập</p><h1>Chào mừng trở lại, {name}!</h1><p className="mt-2 max-w-xl">Sẵn sàng tiếp tục hành trình tiếng Anh hôm nay?</p><Link href={upcoming[0]?.url ?? '/student/lessons'} className="btn mt-5 inline-flex bg-white text-indigo-700 shadow-sm hover:bg-indigo-50">Tiếp tục học <ArrowRight size={16}/></Link></div><div className="student-hero-art" aria-hidden="true"><span>ABC</span><i>+</i></div></Card><div className="student-section-heading mt-8"><h2>Bài học cần hoàn thành</h2><Link href="/student/lessons" className="text-sm font-semibold text-indigo-600">Xem tất cả</Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{upcoming.slice(0,3).map((item,index)=><Card key={`${item.title}-${index}`} className="student-mission-card"><span className="student-skill-icon">{index===0?'READ':index===1?'GRAM':'A+'}</span><p className="mt-4 text-xs font-semibold uppercase tracking-wide text-indigo-600">Nhiệm vụ hôm nay</p><h3 className="mt-1 text-lg font-semibold text-slate-900">{item.title}</h3><p className="mt-1 text-sm text-slate-500">{item.classroom} · Hạn {item.dueAt ? new Date(item.dueAt).toLocaleDateString('vi-VN') : 'Chưa đặt hạn'}</p><Link href={item.url ?? '/student/lessons'} className="btn btn-primary mt-4 w-full">{item.actionLabel ?? 'Bắt đầu làm bài'} <ArrowRight size={15}/></Link></Card>)}{!upcoming.length&&<div className="md:col-span-2 xl:col-span-3"><EmptyState title="Bạn đã hoàn thành mọi nhiệm vụ!" description="Bài học mới sẽ xuất hiện tại đây khi giáo viên giao bài."/></div>}</div><div className="student-section-heading mt-8"><h2>Tiến độ của bạn</h2><Link href="/student/grades" className="text-sm font-semibold text-indigo-600">Xem kết quả</Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(stats).slice(0,4).map(([label,value])=><Card key={label} className="student-stat-card"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p></Card>)}</div>{recent.length>0&&<Recent items={recent}/>}</AppShell>}
function Upcoming({items}: {items: Props['upcoming']}){return <Card className="p-5"><div className="mb-4 flex items-center gap-2"><CalendarClock className="text-teal-600" size={20}/><h2 className="section-title">Hạn sắp tới</h2></div>{items.length?<div className="space-y-3">{items.map((item,index)=><div key={index} className="rounded-xl bg-slate-50 p-4"><p className="font-medium text-slate-900">{item.title}</p><p className="mt-1 text-sm text-slate-500">{item.classroom} · {item.dueAt ? new Date(item.dueAt).toLocaleString('vi-VN') : 'Chưa đặt hạn'}</p>{item.url&&<Link href={item.url} className="mt-2 inline-flex items-center gap-1 text-sm font-medium text-indigo-600">Mở <ArrowRight size={15}/></Link>}</div>)}</div>:<EmptyState title="Không có hạn sắp tới" description="Hiện không còn việc nào cần xử lý."/>}</Card>}
function Recent({items}: {items: Props['recent']}){return <Card className="mt-6 p-5"><h2 className="section-title">Hoạt động gần đây</h2><div className="mt-4 divide-y divide-slate-100">{items.map((item,index)=><div key={index} className="flex justify-between gap-4 py-3 text-sm"><span>{item.action.replaceAll('_',' ')}</span><span className="text-slate-500">{new Date(item.at).toLocaleString('vi-VN')}</span></div>)}</div></Card>}
