import AppShell from '@/Layouts/AppShell';
import { Badge, Card, EmptyState, PageHeader, Pagination } from '@/Components/ui';
import { Head, Link } from '@inertiajs/react';
import { ArrowRight, Clock } from 'lucide-react';
import { useEffect, useState } from 'react';
type Delivery = { id: number; status: string; due_at?: string; open_at?: string; classroom?: { name: string }; assignment_version?: { total_points: string; assignment?: { title: string; description?: string } } };
export default function Assignments({ deliveries }: { deliveries: { data: Delivery[]; links: Array<{ url: string | null; label: string; active: boolean }> } }) {
    const [now, setNow] = useState(() => Date.now());
    useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 30000); return () => window.clearInterval(timer); }, []);
    const statusLabel = (status: string, upcoming: boolean) => upcoming ? 'Sắp mở' : ({ OPEN: 'Có thể làm', SCHEDULED: 'Có thể làm', COMPLETED: 'Đã hoàn thành', OVERDUE: 'Quá hạn' }[status] || status);
    return <AppShell><Head title="Bài học" /><PageHeader title="Bài học được giao" description="Theo dõi các bài học cần hoàn thành trong lớp của bạn." /><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{deliveries.data.map((d) => { const openAt = d.open_at ? new Date(d.open_at) : null; const upcoming = Boolean(openAt && openAt.getTime() > now); return <Card key={d.id} className="student-card student-task-card"><div className="flex items-start justify-between gap-3"><h2 className="text-lg font-semibold text-slate-900">{d.assignment_version?.assignment?.title ?? 'Bài học'}</h2><Badge value={statusLabel(d.status, upcoming)} /></div><p className="mt-2 text-sm text-slate-500">{d.classroom?.name ?? 'Lớp học'} · {d.assignment_version?.total_points ?? 0} điểm</p><p className="mt-4 flex items-center gap-2 text-sm font-medium text-amber-700"><Clock size={16} />{upcoming && openAt ? `Mở lúc ${openAt.toLocaleString('vi-VN')}` : d.due_at ? `Hạn ${new Date(d.due_at).toLocaleString('vi-VN')}` : 'Không có hạn nộp'}</p><div className="student-card-action">{upcoming ? <button type="button" disabled className="btn btn-secondary btn-lg w-full cursor-not-allowed opacity-70">Chưa đến giờ mở</button> : <Link href={`/student/assignments/${d.id}`} className="btn btn-primary btn-lg w-full">Bắt đầu / tiếp tục <ArrowRight size={16} /></Link>}</div></Card>; })}{!deliveries.data.length && <div className="md:col-span-2"><EmptyState title="Chưa có bài học khả dụng" description="Bài học mới từ các lớp của bạn sẽ xuất hiện ở đây khi giáo viên giao bài." /></div>}</div><Pagination links={deliveries.links} /></AppShell>;
}
