import AppShell from '@/Layouts/AppShell';
import { Card, EmptyState, PageHeader, Pagination } from '@/Components/ui';
import { Head } from '@inertiajs/react';

type Grade = { id: number; final_score: string; released_at: string; general_feedback?: string; submission?: { delivery?: { assignment_version?: { total_points?: string; assignment?: { title?: string } } } } };
export default function Grades({ grades }: { grades?: { data?: Grade[]; links?: Array<{ url: string | null; label: string; active: boolean }> } }) {
    const rows = grades?.data ?? [];
    return <AppShell><Head title="Điểm số" /><PageHeader title="Điểm số của tôi" description="Các kết quả đã được giáo viên phát hành sẽ hiển thị ở đây." /><div className="mt-6 space-y-4">{rows.map((grade) => { const max = Number(grade.submission?.delivery?.assignment_version?.total_points ?? 0); const score = Number(grade.final_score ?? 0); const title = grade.submission?.delivery?.assignment_version?.assignment?.title ?? 'Bài học'; return <Card key={grade.id} className="student-card"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold text-slate-900">{title}</h2><p className="mt-1 text-sm text-slate-500">Phát hành {grade.released_at ? new Date(grade.released_at).toLocaleDateString('vi-VN') : '—'}</p></div><div className="rounded-xl bg-indigo-50 px-4 py-3 text-left sm:text-right"><p className="text-2xl font-semibold text-indigo-600">{score} / {max || '—'}</p><p className="text-sm text-slate-500">{max ? `${Math.round(score / max * 100)}%` : 'Đang cập nhật'}</p></div></div>{grade.general_feedback && <div className="mt-4 rounded-xl bg-indigo-50 p-4 text-sm text-indigo-900"><span className="font-medium">Nhận xét của giáo viên: </span>{grade.general_feedback}</div>}</Card>; })}{!rows.length && <EmptyState title="Chưa có điểm được phát hành" description="Giáo viên sẽ phát hành kết quả sau khi hoàn tất chấm điểm." />}</div><Pagination links={grades?.links ?? []} /></AppShell>;
}
