import AppShell from '@/Layouts/AppShell';
import { Badge, Button, Card, EmptyState, PageHeader } from '@/Components/ui';
import { Head, useForm } from '@inertiajs/react';
import { FormEvent } from 'react';
import { Plus, Upload, Users } from 'lucide-react';

type Classroom = { id: number; name: string; code: string; status: string; student_count: number; teacher_count: number; course_version: { title: string; course: { title: string } }; primary_teacher?: { name: string } };
type Option = { id: number; name?: string; title?: string; code?: string; course?: { title: string } };

export default function Classrooms({ classrooms, courseVersions, teachers }: { classrooms: { data: Classroom[] }; courseVersions: Option[]; teachers: Option[] }) {
    const form = useForm({ name: '', code: '', course_version_id: '', primary_teacher_id: '', description: '', start_date: '', end_date: '' });
    const upload = useForm<{ file: File | null }>({ file: null });
    const submit = (e: FormEvent) => { e.preventDefault(); form.post('/admin/classrooms', { onSuccess: () => form.reset() }); };
    const importStudents = (e: FormEvent) => { e.preventDefault(); upload.post('/admin/classrooms/import-students', { forceFormData: true, onSuccess: () => upload.reset() }); };
    return <AppShell><Head title="Lớp học" /><PageHeader title="Lớp học" description="Quản lý lớp và danh sách học sinh trong trung tâm." actions={<a href="#create-classroom" className="btn-primary"><Plus size={17} />Lớp học mới</a>} />
        <Card className="mt-6 border-indigo-100 bg-indigo-50/60 p-5"><div className="flex items-start gap-3"><div className="rounded-xl bg-white p-3 text-indigo-600"><Upload size={20} /></div><div><h2 className="font-semibold text-slate-900">Import học sinh hàng loạt</h2><p className="mt-1 text-sm text-slate-600">Tải file CSV hoặc XLSX gồm các cột: <b>class_name, student_name, email, password</b>. Mỗi dòng sẽ tạo tài khoản và ghi danh ACTIVE.</p><form onSubmit={importStudents} className="mt-4 flex flex-wrap items-center gap-3"><a href="/admin/classrooms/import-students/template" className="btn btn-outline">Tải file mẫu</a><input type="file" accept=".csv,.xlsx" className="field max-w-sm bg-white" onChange={e => upload.setData('file', e.target.files?.[0] ?? null)} required /><Button type="submit" loading={upload.processing} leadingIcon={<Upload size={16} />}>Import danh sách</Button></form>{upload.errors.file && <p className="mt-2 text-sm text-red-600">{upload.errors.file}</p>}</div></div></Card>
        <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{classrooms.data.map(c => <Card key={c.id} className="p-5"><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold text-indigo-600">{c.code}</p><h2 className="mt-1 text-lg font-semibold">{c.name}</h2></div><Badge value={c.status} /></div><p className="mt-3 text-sm text-slate-500">{c.course_version.course.title} · {c.course_version.title}</p><div className="mt-5 flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><span><Users className="mr-1 inline" size={16} />{c.student_count} học sinh</span><span>{c.primary_teacher?.name || 'Chưa phân công giáo viên'}</span></div></Card>)}{!classrooms.data.length && <div className="md:col-span-2"><EmptyState title="Chưa có lớp học" description="Tạo lớp đầu tiên để bắt đầu quản lý học sinh." /></div>}</div>
        <Card id="create-classroom" className="mt-6 p-5"><h2 className="section-title">Tạo lớp học</h2><form onSubmit={submit} className="mt-5 grid gap-4 md:grid-cols-2"><label><span className="label">Tên lớp *</span><input className="field" value={form.data.name} onChange={e => form.setData('name', e.target.value)} required /></label><label><span className="label">Mã lớp *</span><input className="field" value={form.data.code} onChange={e => form.setData('code', e.target.value)} required /></label><label><span className="label">Phiên bản khóa học *</span><select className="field" value={form.data.course_version_id} onChange={e => form.setData('course_version_id', e.target.value)} required><option value="">Chọn phiên bản khóa học</option>{courseVersions.map(v => <option key={v.id} value={v.id}>{v.course?.title} · {v.title}</option>)}</select></label><label><span className="label">Giáo viên chính</span><select className="field" value={form.data.primary_teacher_id} onChange={e => form.setData('primary_teacher_id', e.target.value)}><option value="">Phân công sau</option>{teachers.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label><span className="label">Ngày bắt đầu</span><input type="date" className="field" value={form.data.start_date} onChange={e => form.setData('start_date', e.target.value)} /></label><label><span className="label">Ngày kết thúc</span><input type="date" className="field" value={form.data.end_date} onChange={e => form.setData('end_date', e.target.value)} /></label><div className="md:col-span-2"><Button type="submit" loading={form.processing}>Tạo lớp học</Button></div></form></Card>
    </AppShell>;
}
