import AppShell from '@/Layouts/AppShell';
import { Card, EmptyState, PageHeader } from '@/Components/ui';
import { Head, router, usePage } from '@inertiajs/react';
import { BarChart3, Filter, Users } from 'lucide-react';
import { PageProps } from '@/types';
import type { ReactNode } from 'react';

type Group = { classroom: string; lesson: string; students: number; submitted: number; graded: number; average_score: string | number | null; max_score: string | number | null };
type Option = { id: number; name?: string; title?: string };
type Props = { groups?: Group[]; classrooms?: Option[]; lessons?: Option[]; filters?: { classroom_id?: string; lesson_id?: string } };

export default function Gradebook({ groups = [], classrooms = [], lessons = [], filters = {} }: Props) {
    const { auth } = usePage<PageProps>().props;
    const prefix = auth.role === 'ADMIN' ? '/admin' : '/teacher';
    const apply = (key: 'classroom_id' | 'lesson_id', value: string) => router.get(`${prefix}/gradebook`, { ...filters, [key]: value || undefined }, { preserveState: true, replace: true });
    return <AppShell><Head title="Sổ điểm" /><PageHeader title="Sổ điểm theo lớp và bài học" description="Tổng hợp điểm thật từ các bài nộp của học sinh." /><div className="mt-6 grid gap-4 sm:grid-cols-3"><Summary label="Nhóm lớp · bài học" value={groups.length} icon={<BarChart3 size={19} />} /><Summary label="Học sinh đã nộp" value={groups.reduce((total, group) => total + group.submitted, 0)} icon={<Users size={19} />} /><Summary label="Đã chấm" value={groups.reduce((total, group) => total + group.graded, 0)} icon={<BarChart3 size={19} />} /></div><Card className="mt-6 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-slate-700"><Filter size={17} /> Lọc sổ điểm</div><div className="mt-3 grid gap-3 md:grid-cols-2"><select className="field" value={filters.classroom_id ?? ''} onChange={(event) => apply('classroom_id', event.target.value)} aria-label="Lọc theo lớp"><option value="">Tất cả lớp phụ trách</option>{classrooms.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field" value={filters.lesson_id ?? ''} onChange={(event) => apply('lesson_id', event.target.value)} aria-label="Lọc theo bài học"><option value="">Tất cả bài học</option>{lessons.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></div></Card><Card className="mt-4 overflow-hidden">{groups.length ? <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Lớp</th><th className="px-5 py-3">Bài học</th><th className="px-5 py-3">Học sinh</th><th className="px-5 py-3">Đã nộp</th><th className="px-5 py-3">Đã chấm</th><th className="px-5 py-3">Điểm trung bình</th></tr></thead><tbody className="divide-y divide-slate-100">{groups.map((group, index) => <tr key={`${group.classroom}-${group.lesson}-${index}`}><td className="px-5 py-4 font-medium text-slate-800">{group.classroom}</td><td className="px-5 py-4 text-slate-700">{group.lesson}</td><td className="px-5 py-4">{group.students}</td><td className="px-5 py-4">{group.submitted}</td><td className="px-5 py-4">{group.graded}</td><td className="px-5 py-4 font-semibold text-indigo-600">{group.average_score === null ? 'Chưa có điểm' : `${group.average_score} / ${group.max_score ?? '—'}`}</td></tr>)}</tbody></table></div> : <div className="p-6"><EmptyState title="Chưa có dữ liệu sổ điểm" description="Sổ điểm sẽ tự cập nhật khi học sinh nộp bài và giáo viên chấm điểm." /></div>}</Card></AppShell>;
}
function Summary({ label, value, icon }: { label: string; value: number; icon: React.ReactNode }) { return <Card className="p-4"><div className="flex items-center gap-3 text-indigo-600"><span className="rounded-lg bg-indigo-50 p-2">{icon}</span><div><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-semibold text-slate-900">{value}</p></div></div></Card>; }
