import { Link, router, usePage } from '@inertiajs/react';
import { ReactNode, useEffect, useRef, useState } from 'react';
import { LayoutDashboard, Users, GraduationCap, School, BookOpen, PanelsTopLeft, FileCheck2, Trophy, CircleHelp, Files, Sparkles, BarChart3, ScrollText, Settings, Menu, X, Bell, ChevronDown, LogOut, UserRound, PanelLeftClose } from 'lucide-react';
import { PageProps } from '@/types';
const config = {
 ADMIN: [['Bảng điều khiển','/admin/dashboard',LayoutDashboard],['Giáo viên','/admin/teachers',Users],['Học sinh','/admin/students',GraduationCap],['Lớp học','/admin/classrooms',School],['Khóa học','/admin/courses',BookOpen],['Trình xây dựng bài tập','/admin/lessons',PanelsTopLeft],['Bài nộp','/admin/submissions',FileCheck2],['Sổ điểm','/admin/gradebook',Trophy],['Ngân hàng câu hỏi','/admin/questions',CircleHelp],['Tài liệu','/admin/documents',Files],['Tạo câu hỏi bằng AI','/admin/ai-generator',Sparkles],['Báo cáo','/admin/reports',BarChart3],['Nhật ký hệ thống','/admin/audit-logs',ScrollText],['Cài đặt trung tâm','/admin/settings/center',Settings]],
 TEACHER: [['Bảng điều khiển','/teacher/dashboard',LayoutDashboard],['Lớp của tôi','/teacher/classes',School],['Học sinh của tôi','/teacher/students',GraduationCap],['Trình xây dựng bài tập','/teacher/lessons',PanelsTopLeft],['Bài nộp','/teacher/submissions',FileCheck2],['Sổ điểm','/teacher/gradebook',Trophy],['Ngân hàng câu hỏi','/teacher/questions',CircleHelp],['Tài liệu','/teacher/documents',Files],['Tạo câu hỏi bằng AI','/teacher/ai-generator',Sparkles],['Báo cáo','/teacher/reports',BarChart3]],
 STUDENT: [['Trang chủ','/student/dashboard',LayoutDashboard],['Học tập','/student/classes',School],['Bài học','/student/lessons',BookOpen],['Kết quả','/student/grades',Trophy],['Hồ sơ','/profile',UserRound]],
} as const;
export default function AppShell({ children }: { children: ReactNode }) {
 const page=usePage<PageProps>();const {auth,appName,center,flash,notifications}=page.props;const url=page.url;const [mobileOpen,setMobileOpen]=useState(false);const [collapsed,setCollapsed]=useState(false);const [accountOpen,setAccountOpen]=useState(false);const closeButton=useRef<HTMLButtonElement>(null);
 useEffect(()=>setMobileOpen(false),[url]);useEffect(()=>{if(mobileOpen){document.body.style.overflow='hidden';setTimeout(()=>closeButton.current?.focus(),0);}else document.body.style.overflow='';return()=>{document.body.style.overflow='';};},[mobileOpen]);const nav=config[auth.role];
 const sidebar=(mobile=false)=><aside className={`${collapsed&&!mobile?'w-20':'w-64'} flex h-full flex-col bg-slate-950 text-slate-200`} aria-label="Điều hướng chính"><div className="flex h-16 items-center gap-3 border-b border-slate-800 px-4">{center?.logoUrl ? <img src={center.logoUrl} alt="" className="h-9 w-9 shrink-0 rounded-xl object-contain bg-white p-1" /> : <div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-500 font-semibold text-white">EC</div>}{(!collapsed||mobile)&&<span className="truncate font-semibold text-white">{center?.name ?? appName}</span>}{mobile&&<button ref={closeButton} onClick={()=>setMobileOpen(false)} className="ml-auto rounded-lg p-2" aria-label="Đóng điều hướng"><X size={20}/></button>}</div><nav className="flex-1 space-y-1 overflow-y-auto p-3">{nav.map(([label,href,Icon])=>{const active=url===href||url.startsWith(`${href}/`);return <Link key={href} href={href} aria-current={active?'page':undefined} title={collapsed&&!mobile?label:undefined} className={`flex min-h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium ${active?'bg-indigo-500 text-white':'text-slate-300 hover:bg-slate-800 hover:text-white'}`}><Icon size={19}/>{(!collapsed||mobile)&&<span>{label}</span>}</Link>;})}</nav>{!mobile&&<button onClick={()=>setCollapsed(v=>!v)} className="m-3 flex min-h-10 items-center justify-center gap-2 rounded-lg border border-slate-700 text-sm hover:bg-slate-800" aria-label={collapsed?'Mở rộng thanh bên':'Thu gọn thanh bên'} aria-expanded={!collapsed}><PanelLeftClose size={18}/>{!collapsed&&'Thu gọn'}</button>}</aside>;
 return <div className={`min-h-screen ${auth.role==='STUDENT'?'student-workspace':''}`}><div className="fixed inset-y-0 left-0 z-30 hidden lg:block">{sidebar()}</div>{mobileOpen&&<div className="fixed inset-0 z-50 lg:hidden" role="dialog" aria-modal="true"><button className="absolute inset-0 bg-slate-950/55" aria-label="Đóng điều hướng" onClick={()=>setMobileOpen(false)}/><div className="relative h-full w-72 max-w-[85vw]">{sidebar(true)}</div></div>}<div className={`min-h-screen transition-[padding] ${collapsed?'lg:pl-20':'lg:pl-64'}`}><header className="sticky top-0 z-20 flex h-16 items-center gap-3 border-b border-slate-200 bg-white/95 px-4 backdrop-blur sm:px-6"><button onClick={()=>setMobileOpen(true)} className="btn btn-ghost btn-icon lg:hidden" aria-label="Mở điều hướng"><Menu size={21}/></button><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-900">{auth.role==='STUDENT'?'Không gian học tập':'Không gian trung tâm'}</p></div><Link href="/notifications" className="btn btn-ghost btn-icon relative" aria-label={`${notifications.unreadCount} thông báo chưa đọc`}><Bell size={20}/>{notifications.unreadCount>0&&<span className="absolute right-1 top-1 h-2.5 w-2.5 rounded-full bg-red-500 ring-2 ring-white"/>}</Link><div className="relative"><button onClick={()=>setAccountOpen(v=>!v)} className="btn btn-ghost flex items-center gap-2 px-2 py-1.5" aria-expanded={accountOpen}><div className="grid h-9 w-9 place-items-center rounded-full bg-indigo-100 font-medium text-indigo-700">{auth.user.name.charAt(0)}</div><span className="hidden text-left sm:block"><span className="block text-sm font-medium text-slate-900">{auth.user.name}</span><span className="block text-xs text-slate-500">{auth.role}</span></span><ChevronDown size={16}/></button>{accountOpen&&<div className="absolute right-0 mt-2 w-52 rounded-xl border border-slate-200 bg-white p-2 shadow-xl"><Link href="/profile" className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm hover:bg-slate-50"><UserRound size={17}/>Hồ sơ</Link><button onClick={()=>router.post('/logout')} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-sm text-red-600 hover:bg-red-50"><LogOut size={17}/>Đăng xuất</button></div>}</div></header><main className="app-main">{flash.success&&<div role="status" className="alert alert-success mb-5">{flash.success}</div>}{flash.error&&<div role="alert" className="alert alert-error mb-5">{flash.error}</div>}{children}</main>{auth.role==='STUDENT'&&<nav className="student-bottom-nav" aria-label="Điều hướng học tập">{nav.slice(0,5).map(([label,href,Icon])=>{const active=url===href||url.startsWith(`${href}/`);return <Link key={href} href={href} aria-current={active?'page':undefined} className={active?'is-active':''}><Icon size={19}/><span>{label}</span></Link>})}</nav>}</div></div>;
}
